# Generated by Django 4.2.5 on 2023-10-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, to='blog.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
